### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by jaseemabid** [llvm-hs/llvm-hs-pretty#8] opened 2017-05-31 21:07 UTC
`stack test` fails for me. I have no local changes and is using the current master. 
```
$ llc --version
LLVM (http://llvm.org/):
  LLVM version 4.0.0
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: skylake
```
This is the complete build log. 

```
Test: tests/input/intrinsic.ll
================================================================================
tests/input/intrinsic.ll
================================================================================
Module
  { moduleName = "<string>"
  , moduleSourceFileName = "<string>"
  , moduleDataLayout = Nothing
  , moduleTargetTriple = Nothing
  , moduleDefinitions =
      [ GlobalDefinition
          Function
            { linkage = External
            , visibility = Default
            , dllStorageClass = Nothing
            , callingConvention = C
            , returnAttributes = []
            , returnType =
                FloatingPointType { typeBits = 64 , floatingPointFormat = IEEE }
            , name = Name "llvm.sqrt.f64"
            , parameters =
                ( [ Parameter
                      FloatingPointType { typeBits = 64 , floatingPointFormat = IEEE }
                      (UnName 0)
                      []
                  ]
                , False
                )
            , functionAttributes = [ Left (GroupID 0) ]
            , section = Nothing
            , comdat = Nothing
            , alignment = 0
            , garbageCollectorName = Nothing
            , prefix = Nothing
            , basicBlocks = []
            , personalityFunction = Nothing
            }
      , GlobalDefinition
          Function
            { linkage = External
            , visibility = Default
            , dllStorageClass = Nothing
            , callingConvention = C
            , returnAttributes = []
            , returnType =
                FloatingPointType { typeBits = 64 , floatingPointFormat = IEEE }
            , name = Name "main"
            , parameters = ( [] , False )
            , functionAttributes = []
            , section = Nothing
            , comdat = Nothing
            , alignment = 0
            , garbageCollectorName = Nothing
            , prefix = Nothing
            , basicBlocks =
                [ BasicBlock
                    (Name "entry")
                    [ UnName 0 :=
                        Call
                          { tailCallKind = Nothing
                          , callingConvention = C
                          , returnAttributes = []
                          , function =
                              Right
                                (ConstantOperand
                                   (GlobalReference
                                      PointerType
                                        { pointerReferent =
                                            FunctionType
                                              { resultType =
                                                  FloatingPointType
                                                    { typeBits = 64 , floatingPointFormat = IEEE }
                                              , argumentTypes =
                                                  [ FloatingPointType
                                                      { typeBits = 64 , floatingPointFormat = IEEE }
                                                  ]
                                              , isVarArg = False
                                              }
                                        , pointerAddrSpace = AddrSpace 0
                                        }
                                      (Name "llvm.sqrt.f64")))
                          , arguments =
                              [ ( ConstantOperand Float { floatValue = Double 2.0 } , [] ) ]
                          , functionAttributes = []
                          , metadata = []
                          }
                    ]
                    (Do
                       Ret
                         { returnOperand =
                             Just
                               (LocalReference
                                  FloatingPointType { typeBits = 64 , floatingPointFormat = IEEE }
                                  (UnName 0))
                         , metadata' = []
                         })
                ]
            , personalityFunction = Nothing
            }
      , FunctionAttributes (GroupID 0) [ NoUnwind , ReadNone ]
      ]
  }
; ModuleID = '<string>'

declare external double @"llvm.sqrt.f64"(double)

define external double @main(){
entry:
  %0 = call double @"llvm.sqrt.f64"(double 2.000000e0)
  ret double %0
}

attributes #0 = {nounwind readnone}
Round Tripped!
Test: tests/input/comparison.ll
================================================================================
tests/input/comparison.ll
================================================================================
Error reading input:
<string>:7:18: error: expected comma after load's type
  %0 = load i32* %x.addr
                 ^

```

**Comment by cocreature** [comment] 2017-06-01 06:14
This is a duplicate of #5

**Closed by cocreature** 2017-06-01 06:14 UTC

**Comment by sdiehl** [comment] 2017-06-01 11:01
Yeah, the answer to this is simply that the IR isn't fully mapped yet. Happy to take pull requests if you fancy isolating this failure, it's probably trivial to adjust the pretty printer. :-)
